
#' Find a keyword in names or labels of
#' Trouver un mot-clé dans les noms ou labels des tables chargées
#'
#' @param keyword the keyword to search for
#' @param data the dataframe where to look, generated by [read_trialmaster()]
#' @param ignore_case should case differences be ignored in the match?
#'
#' @return a filtered tibble
#' @export
#' @examples 
#' library(crosstable)
#' library(dplyr)
#' library(purrr)
#' #for this example, tablelist comes from `{crosstable}` but it should come 
#' #from [read_trialmaster()] and be left as default
#' mtcars2 = crosstable::mtcars2
#' iris2 = crosstable::iris2
#' tablelist = tibble(
#'   dataset=c("mtcars2", "iris2"),
#'   names=map(dataset, ~names(get(.x))), 
#'   labels=map(dataset, ~labelled::var_label(get(.x)))
#' )
#' find_keyword("hp", data=tablelist)
#' find_keyword("number|date", data=tablelist)
#' find_keyword("number|date", data=tablelist, ignore_case=FALSE)
find_keyword = function(keyword, data=getOption("tablelist", NULL), ignore_case=TRUE){
  stopifnot(!is.null(data))
  f = if(isTRUE(ignore_case)) tolower else identity
  
  data %>% 
    unnest(c(names, labels)) %>% 
    mutate(labels=unlist(labels)) %>% 
  # mutate(labels=map_chr(labels, ~ifelse(is.null(.x), NA, .x))) %>%  #better ? 
    filter(str_detect(f(names), f(keyword)) |
             str_detect(f(labels), f(keyword)))
}


#' Load a list in an environment
#'
#' @param x a list
#' @param env the environement onto which the list shoudl be loaded
#' @param remove if `TRUE`, `x` will be removed from the environment afterward
#'
#' @return nothing, called for its side-effect
#' @export
#'
#' @examples
#' 
#' x=list(a=1, b=mtcars)
#' load_list(x, remove=FALSE)
#' print(a)
#' print(nrow(b))
#' 
load_list = function(x, env=parent.frame(), remove=TRUE){
  nz = nzchar(names(x))
  if(any(!nz)){
    cli_abort(c("Every member of {.arg x} should have a name.", 
                i="Unnamed member{?s} ind{?ex/ices} of {.arg x}: {as.character(which(!nz))}"), 
              class="load_list_unnamed_error")
  }
  list2env(x, env)
  if(remove) remove(list=vname(x), envir=env)
}

#' Load a `.RData` file as a list
#' 
#' Instead of loading a `.RData` file in the global environment, extract every object into a list.
#'
#' @param filename the filename, with the `.RData` extention.
#'
#' @return a list
#' @export
#'
#' @examples
#' 
#' x = list(a=1, b=mtcars)
#' save_list(x, "test.RData")
#' y = load_as_list("test.RData")
#' print(y$a)
load_as_list = function(filename){
  load(filename,  temp_env <- new.env())
  as.list(temp_env)
}

#' Save a list as `.RData` file
#'
#' @param x a list
#' @param filename the filename, with the `.RData` extention.
#'
#' @return nothing, called for its side-effect
#' @export
#'
#' @examples
#' x=list(a=1, b=mtcars)
#' save_list(x, "test.RData")
#' load("test.RData")
#' file.remove("test.RData")
#' print(a)
#' print(nrow(b))
save_list = function(x, filename){
  if(!str_ends(tolower(filename), "\\.rdata")){
    cli_abort(c("{.val filename} should have the `.RData` extension.", 
                i="Current filename: {.val {filename}}"))
  }
  save(list=names(x), file=filename, envir=as.environment(x))
}
