
name: Bump dev version

on:
  workflow_run:
    workflows: ["R-CMD-check"]
    types:
      - completed
      
jobs:
  update_version:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
    - name: Bump dev version
      uses: DanChaltiel/actions/bump-dev-version@v3
      with:
        create-tag: 'true'
        update-readme: 'true'
