on: push

name: Update dev version

jobs:
  update_version:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        
      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: desc
        
      - name: Update version
        run: |
          #install.packages("desc")
          desc::desc_bump_version("dev")
        shell: Rscript {0}
        
      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.5.0
        with:
          default_author: github_actions
          message: 'Update dev version (Github Actions)'
